### **Задание на повторение материала
### Задание 1 
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [1]:
import numpy as np

In [3]:
a = np.arange(12,24,1)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


### Задание 2
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [12]:
b = a.reshape(2, 6)
c = a.reshape(3, 4)
d = a.reshape(4, 3)
e = a.reshape(6, 2)
f = a.reshape(12, 1)
print(b)
print('\n',c)
print('\n',d)
print('\n',e)
print('\n',f)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]

 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


### Задание 3
Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [17]:
b = a.reshape(2, -1)
c = a.reshape(3, -1)
d = a.reshape(4, -1)
e = a.reshape(-1, 2)
f = a.reshape(-1, 1)
print(b)
print('\n',c)
print('\n',d)
print('\n',e)
print('\n',f)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]

 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


### Задание 4
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [21]:
print('Нет, размерность массива f равна {}'.format(f.ndim))
print('В то же время размерность массива a равна {}'.format(a.ndim))

Нет, размерность массива f равна 2
В то же время размерность массива a равна 1


### Задание 5
Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [35]:
g = np.random.sample((3, 4))

print(g)
g_size = g.size # кол-во элементов
print(g_size)

[[0.12251166 0.24925996 0.44800515 0.34942652]
 [0.59710254 0.2004451  0.51643143 0.94065888]
 [0.47381747 0.82294061 0.26525305 0.47595847]]
12


In [38]:
#g_reshape = np.array(g.reshape(1, g_size)) # всё равно получается двумерным с одной строкой
g_reshape = g.ravel() # Преобразование в двумерный
print(g_reshape)
g_reshape.ndim

[0.12251166 0.24925996 0.44800515 0.34942652 0.59710254 0.2004451
 0.51643143 0.94065888 0.47381747 0.82294061 0.26525305 0.47595847]


1

### Задание 6
Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [73]:
a = np.arange(20,0,-2)
print(a)
#a.size
a.ndim
#type(a)
#a.shape

[20 18 16 14 12 10  8  6  4  2]


1

### Задание 7 
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [77]:
#b = np.arange(20,1,-2)
#b = np.array([i for i in range(20,1,-2)])
#print(b)
#b.size
#b.ndim
#type(b)
#b.shape
b = np.arange(20, 1, -2).reshape(1, 10)
print(b,'\n')
print('Размерность a = {}'.format(a.ndim),', а размерность b = {}'.format(b.ndim),
      '\nshape a = {}'.format(a.shape),', а shape b = {}'.format(b.shape))
#b.ndim
#type(b)
#b.shape

[[20 18 16 14 12 10  8  6  4  2]] 

Размерность a = 1 , а размерность b = 2 
shape a = (10,) , а shape b = (1, 10)


### Задание 8
Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [78]:
a = np.zeros((2, 2))
print(a)
b = np.ones((3, 2))
print('\n',b)

[[0. 0.]
 [0. 0.]]

 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [82]:
v = np.concatenate((a,b), axis=0)
print(v)
v.size

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


10

### Задание 9
Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [85]:
a = np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [87]:
A = a.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [89]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [95]:
B = A.dot(At)
print(B)
B.shape

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


(4, 4)

In [101]:
d = np.linalg.det(B)

print('Не получится вычислить обратную матрицу, так как определитель матрицы B равен {}'.format(int(d)))

Не получится вычислить обратную матрицу, так как определитель матрицы B равен 0


### Задание 10
Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [143]:
np.random.seed(42)
np.random.rand(4)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239])

### Задание 11
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [154]:
c = np.random.randint(1,16,16)
c

array([ 2,  9, 13, 15, 12, 10, 12, 15, 15, 15,  1,  8,  1,  6, 12, 11])

### Задание 12
Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [156]:
C = c.reshape(4,4)
C

array([[ 2,  9, 13, 15],
       [12, 10, 12, 15],
       [15, 15,  1,  8],
       [ 1,  6, 12, 11]])

In [158]:
D = B +(C.dot(10))
D

array([[ 25, 104, 153, 182],
       [134, 150, 206, 272],
       [173, 236, 159, 292],
       [ 42, 182, 332, 412]])

In [159]:
D_det = np.linalg.det(D) # Определитель
print(D_det)

76722600.0000002


In [160]:
r = np.linalg.matrix_rank(D) # Ранг матрицы D
print(r)

4


In [161]:
D_inv = np.linalg.inv(D) # Обратная матрица
print(D_inv)

[[-0.00465208  0.01331368 -0.00268708 -0.00483013]
 [ 0.03340241 -0.00751773  0.00407442 -0.01267997]
 [ 0.03811289  0.0144492  -0.01243597 -0.01756171]
 [-0.04499352 -0.00967981  0.00849528  0.02267259]]


### Задание 13
Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [172]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.]])

In [176]:
print(B)
print('\n',C)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]

 [[ 2  9 13 15]
 [12 10 12 15]
 [15 15  1  8]
 [ 1  6 12 11]]


In [177]:
E = np.where(D_inv, B, C)
E

array([[  2,  14,  13,  15],
       [ 14,  10,  86,  15],
       [ 23,  86,   1,   8],
       [  1,   6, 212, 302]])